/**
 * AUTO-GENERATED FILE
 * Do not modify the EXERCISE_MAPPINGS manually unless adding a specific override.
 * Modify scripts/generateExerciseMappings.js to regenerate.
 */

export const MOVEMENT_PATTERNS = {
  "squat": {
    "type": "squat",
    "joints": [
      23,
      25,
      27
    ],
    "upThreshold": 160,
    "downThreshold": 100,
    "defaultParams": {
      "LERP_SPEED": 0.4,
      "KALMAN_NOISE": 0.1
    },
    "category": "lower_body",
    "startPosition": "up"
  },
  "deadlift": {
    "type": "deadlift",
    "joints": [
      11,
      23,
      25
    ],
    "upThreshold": 170,
    "downThreshold": 120,
    "defaultParams": {
      "LERP_SPEED": 0.4,
      "KALMAN_NOISE": 0.1
    },
    "category": "lower_body",
    "startPosition": "up"
  },
  "lunge": {
    "type": "lunge",
    "joints": [
      23,
      25,
      27
    ],
    "upThreshold": 160,
    "downThreshold": 100,
    "defaultParams": {
      "LERP_SPEED": 0.4,
      "KALMAN_NOISE": 0.1
    },
    "category": "lower_body",
    "startPosition": "up"
  },
  "calf_raise": {
    "type": "calf_raise",
    "joints": [
      25,
      27,
      31
    ],
    "upThreshold": 120,
    "downThreshold": 90,
    "defaultParams": {
      "LERP_SPEED": 0.4,
      "KALMAN_NOISE": 0.1
    },
    "category": "lower_body",
    "startPosition": "down"
  },
  "curl": {
    "type": "curl",
    "joints": [
      11,
      13,
      15
    ],
    "upThreshold": 35,
    "downThreshold": 150,
    "defaultParams": {
      "LERP_SPEED": 0.5,
      "KALMAN_NOISE": 0.05
    },
    "category": "upper_body",
    "startPosition": "down"
  },
  "row": {
    "type": "row",
    "joints": [
      11,
      13,
      15
    ],
    "upThreshold": 80,
    "downThreshold": 160,
    "defaultParams": {
      "LERP_SPEED": 0.5,
      "KALMAN_NOISE": 0.05
    },
    "category": "upper_body",
    "startPosition": "down"
  },
  "pullup": {
    "type": "pullup",
    "joints": [
      11,
      13,
      15
    ],
    "upThreshold": 60,
    "downThreshold": 160,
    "defaultParams": {
      "LERP_SPEED": 0.4,
      "KALMAN_NOISE": 0.1
    },
    "category": "upper_body",
    "startPosition": "down"
  },
  "press": {
    "type": "press",
    "joints": [
      11,
      13,
      15
    ],
    "upThreshold": 160,
    "downThreshold": 90,
    "defaultParams": {
      "LERP_SPEED": 0.5,
      "KALMAN_NOISE": 0.05
    },
    "category": "upper_body",
    "startPosition": "down"
  },
  "pushup": {
    "type": "pushup",
    "joints": [
      11,
      13,
      15
    ],
    "upThreshold": 160,
    "downThreshold": 90,
    "defaultParams": {
      "LERP_SPEED": 0.4,
      "KALMAN_NOISE": 0.1
    },
    "category": "upper_body",
    "startPosition": "up"
  },
  "fly": {
    "type": "fly",
    "joints": [
      11,
      13,
      15
    ],
    "upThreshold": 140,
    "downThreshold": 160,
    "defaultParams": {
      "LERP_SPEED": 0.5,
      "KALMAN_NOISE": 0.05
    },
    "category": "upper_body",
    "startPosition": "down"
  },
  "raise": {
    "type": "raise",
    "joints": [
      23,
      11,
      13
    ],
    "upThreshold": 90,
    "downThreshold": 20,
    "defaultParams": {
      "LERP_SPEED": 0.5,
      "KALMAN_NOISE": 0.05
    },
    "category": "upper_body",
    "startPosition": "down"
  },
  "extension": {
    "type": "extension",
    "joints": [
      11,
      13,
      15
    ],
    "upThreshold": 160,
    "downThreshold": 90,
    "defaultParams": {
      "LERP_SPEED": 0.5,
      "KALMAN_NOISE": 0.05
    },
    "category": "upper_body",
    "startPosition": "down"
  },
  "situp": {
    "type": "situp",
    "joints": [
      11,
      23,
      25
    ],
    "upThreshold": 80,
    "downThreshold": 160,
    "defaultParams": {
      "LERP_SPEED": 0.4,
      "KALMAN_NOISE": 0.1
    },
    "category": "core",
    "startPosition": "down"
  },
  "plank": {
    "type": "plank",
    "joints": [
      11,
      23,
      25
    ],
    "upThreshold": 160,
    "downThreshold": 180,
    "defaultParams": {
      "LERP_SPEED": 0.4,
      "KALMAN_NOISE": 0.1
    },
    "category": "core",
    "startPosition": "up"
  },
  "default": {
    "type": "default",
    "joints": [
      11,
      13,
      15
    ],
    "upThreshold": 45,
    "downThreshold": 160,
    "defaultParams": {
      "LERP_SPEED": 0.4,
      "KALMAN_NOISE": 0.1
    },
    "category": "mixed",
    "startPosition": "down"
  }
};

export const EXERCISE_MAPPINGS = {
  "Dumbbell Curl": "curl",
  "Dumbbell Hammer Curl": "curl",
  "Kettlebell Concentration Curl": "curl",
  "Kettlebell Preacher Curl": "curl",
  "Kettlebell Single Arm Curl": "curl",
  "Band Bayesian Curl": "curl",
  "Band Bayesian Hammer Curl": "curl",
  "Band Bayesian Reverse Curl": "curl",
  "Dumbbell Reverse Curl": "curl",
  "Barbell Reverse Curl": "curl",
  "Dumbbell Single Arm Preacher Curl": "curl",
  "Dumbbell Kneeling Single Arm Row": "row",
  "Dumbbell Laying Incline Row": "row",
  "Dumbbell Single Arm Row": "row",
  "Dumbbell Single Arm Row Knee": "row",
  "Dumbbell Knee Lawnmower Row": "row",
  "Landmine Bicep Curl": "curl",
  "Landmine Concentration Curl": "curl",
  "Vitruvian Row": "row",
  "Kettlebell Row": "row",
  "Cable Archer Row": "row",
  "Cable Bayesian Curl": "curl",
  "Cable Rope Hammer Curl": "curl",
  "Cable Seated Bayesian Curl": "curl",
  "Cable Single Arm Underhand Grip Row": "row",
  "Cable Single Arm Neutral Grip Row": "row",
  "Cable Seated Bayesian Reverse Curl": "curl",
  "Cable Hammer Bayesian Curl": "curl",
  "Barbell Drag Curl": "curl",
  "Landmine T Bar Rows": "row",
  "Neutral Pulldown": "pullup",
  "Underhand Pulldown": "pullup",
  "Kettlebell Single Arm Reverse Curl": "curl",
  "Kettlebell Single Arm Row On Bench": "row",
  "Cardio Band Hammer Curl Jacks": "curl",
  "Cable Pull In": "default",
  "Band Row": "row",
  "Kettlebell Row (Single)": "row",
  "Kettlebell Single Arm Row": "row",
  "Dumbbell Rear Delt Row": "row",
  "Kettlebell Rear Delt Row": "row",
  "Narrow Pulldown": "row",
  "Cardio Row Erg Rower": "row",
  "Cardio Row Erg Rower Arms Only": "row",
  "EZ Bar Preacher Curl": "curl",
  "EZ Bar Reverse Preacher Curl": "curl",
  "Dumbbell Preacher Curl": "curl",
  "Machine Assisted Chin Up": "pullup",
  "Machine Assisted Narrow Pull Up": "row",
  "Machine Assisted Neutral Chin Up": "pullup",
  "Machine Assisted Pull Up": "pullup",
  "Machine Underhand Row": "row",
  "Bodyweight Assisted Chin Up": "pullup",
  "Bodyweight Assisted Gironda Chin Up": "pullup",
  "Bodyweight Assisted Mixed Grip Pullup": "pullup",
  "Bodyweight Assisted Pull Up": "pullup",
  "Bodyweight Inverted Curl": "curl",
  "Bodyweight Close Grip Inverted Curl": "curl",
  "Bodyweight Concentration Curl": "curl",
  "Bodyweight Underhand Inverted Row": "row",
  "Ring Row": "row",
  "Barbell Curl": "curl",
  "Dumbbell Silverback Shrug": "raise",
  "Band Horizontal Shrug": "raise",
  "Barbell Deadlift": "deadlift",
  "Dumbbell Row Bilateral": "row",
  "Kettlebell Silverback Shrug (Single)": "raise",
  "Elevated Pike Press": "press",
  "Band Pull Apart": "raise",
  "Dumbbell Row Unilateral": "row",
  "Kettlebell Silverback Shrug": "raise",
  "Cable Single Arm Rear Delt Row": "row",
  "Dumbbell Seated Rear Delt Row": "row",
  "Bodyweight Pike Press": "press",
  "Bodyweight Overhand Inverted Row": "row",
  "Bodyweight Standing Inverted Row": "row",
  "Supermans": "plank",
  "Kettlebell Swing": "default",
  "Kettlebell Staggered Deadlift (Single)": "deadlift",
  "Kettlebell Goblet Good Morning": "deadlift",
  "Good Mornings": "deadlift",
  "Cable Goblet Squat": "squat",
  "Cable Pull Through": "default",
  "Band Pullthrough": "deadlift",
  "Dumbbell Goblet Good Morning": "deadlift",
  "Barbell Low Bar Good Morning": "deadlift",
  "Barbell Staggered Deadlift": "deadlift",
  "Barbell Single Leg Deadlift": "deadlift",
  "Dumbbell Front Rack Pause Squat": "squat",
  "Dumbbell Single Leg Single Arm Deadlift": "deadlift",
  "Dumbbell Staggered Deadlift": "deadlift",
  "Medicine Ball Single Leg Deadlift": "deadlift",
  "Landmine Snatch": "raise",
  "Vitruvian Romanian Deadlift": "deadlift",
  "Vitruvian Single Leg Deadlift": "deadlift",
  "Vitruvian Staggered Deadlift": "deadlift",
  "Cobra Pose": "situp",
  "Kettlebell Sumo Deadlift": "deadlift",
  "Cable Bar Staggered Romanian Deadlift": "deadlift",
  "Cable Elevated Deadlift": "deadlift",
  "Cable Zercher Squat": "squat",
  "Cable Standing Mid Kickback": "extension",
  "Cable Standing Straight Leg Mid Kickback": "extension",
  "Kettlebell Single Leg Deadlift": "deadlift",
  "Single Legged Romanian Deadlifts": "deadlift",
  "Laying Leg Raises": "raise",
  "Kettlebell Situp": "situp",
  "Band Crunch": "situp",
  "Dumbbell Situp": "situp",
  "Dumbbell Plank Pullthrough": "deadlift",
  "Barbell Situp": "situp",
  "Hollow Hold": "plank",
  "Dumbbell Hollow Hold": "plank",
  "Kettlebell Russian Twist": "situp",
  "Kettlebell Windmill": "default",
  "Dumbbell Russian Twist": "situp",
  "Dumbbell Half Kneeling Wood Chopper": "default",
  "Medicine Ball Plank": "plank",
  "Landmine Hollow Hold": "plank",
  "Medicine Ball Partner Situp Toss": "situp",
  "Landmine Sit Up": "situp",
  "Medicine Ball Slam": "situp",
  "Bosu Ball Forearm Plank": "plank",
  "Bosu Ball Hand Plank": "plank",
  "Vitruvian Crunch": "situp",
  "Bicycle Crunch": "situp",
  "Dead Bug": "situp",
  "Long Lever Forearm Plank": "plank",
  "Bodyweight Knee Plank Up Down": "plank",
  "Bodyweight Plank Up Down": "plank",
  "Rower Knee Tuck": "row",
  "Rower Pike": "row",
  "Kettlebell Windmill Bottom Hand": "default",
  "Barbell Front Squat Olympic": "squat",
  "Kettlebell Front Rack Step Up": "lunge",
  "Cardio Forward Scissor": "default",
  "Cardio In And Out Forward": "default",
  "Alternating Bent Leg Raise": "raise",
  "Bodyweight Hanging Knee Tuck": "situp",
  "Bodyweight Hanging L Sit": "situp",
  "Eccentric Dragonflag": "situp",
  "Elbow Plank Mountain Climber": "plank",
  "Frog Sit Up": "situp",
  "Jumping Mountain Climber": "situp",
  "Reach And Catch": "default",
  "Slow Tempo Mountain Climber": "situp",
  "Sideways Scissor Kick": "situp",
  "Scissor Kick": "situp",
  "Ring Standing Roll Out": "situp",
  "Reverse Crunch Kick Up": "situp",
  "Kettlebell Single Leg Calf Raise": "calf_raise",
  "Kettlebell Calf Raise": "calf_raise",
  "Kettlebell Seated Calf Raise": "calf_raise",
  "Tip Toe Walking": "default",
  "Calf Raises": "calf_raise",
  "Walking Calf Raises": "calf_raise",
  "Barbell Calf Raises": "calf_raise",
  "Band Calf Raise": "calf_raise",
  "Dumbbell Calf Raise": "calf_raise",
  "Dumbbell Seated Calf Raise": "calf_raise",
  "Landmine Calf Raise": "calf_raise",
  "Kettlebell Goblet Calf Raise": "calf_raise",
  "Kettlebell Single Arm Calf Raise": "calf_raise",
  "Kettlebell Single Leg Single Arm Calf Raise": "calf_raise",
  "Treadmill Jog": "squat",
  "Treadmill Walk": "squat",
  "Cardio Figure Eight Sprint": "squat",
  "Cardio In And Outs": "squat",
  "Cardio Lateral Quick Feet": "squat",
  "Cardio Quick Feet": "default",
  "Cardio Sprint In Place": "squat",
  "Machine Horizontal Leg Press Calf Jump": "press",
  "Seated Tibialis Raise": "raise",
  "Standing Tibialis Raise": "raise",
  "Dumbbell Wrist Curl": "curl",
  "Barbell Wrist Curl": "curl",
  "Kettlebell Farmers Carry": "default",
  "Kettlebell Wrist Extension": "extension",
  "Kettlebell Wrist Curl": "curl",
  "Dumbbell Wrist Extension": "extension",
  "Dumbbell Bench Wrist Curl": "curl",
  "Kettlebell Bench Wrist Curl": "curl",
  "Kettlebell Walking Farmers March": "default",
  "Barbell Hip Thrust": "squat",
  "Barbell Curtsy Lunge": "lunge",
  "Barbell Bulgarian Split Squat": "squat",
  "Barbell Front Squat Bodybuilding": "squat",
  "Barbell High Bar Squat": "squat",
  "Landmine Alternating Lunge And Twist": "lunge",
  "Landmine Alternating Lunge To Chest Press": "lunge",
  "Landmine Curtsy Lunge": "lunge",
  "Landmine Goblet Curtsy Lunge": "lunge",
  "Landmine Rotational Lift To Press": "press",
  "Landmine Single Leg Glute Bridge": "squat",
  "Dumbbell Hip Thrust": "squat",
  "Dumbbell Glute Bridge": "squat",
  "Dumbbell Bulgarian Split Squat": "squat",
  "Dumbbell Forward Lunge": "lunge",
  "Dumbbell Goblet Forward Lunge": "lunge",
  "Dumbbell Goblet Reverse Lunge": "lunge",
  "Dumbbell Front Rack Step Up": "lunge",
  "Dumbbell Step Up": "lunge",
  "Glute Bridge": "squat",
  "Bulgarian Split Squat": "squat",
  "Forward Lunges": "lunge",
  "Jump Squats": "squat",
  "Kickbacks": "extension",
  "Assisted Bulgarian Split Squat": "squat",
  "Curtsy Lunge": "lunge",
  "Box Jump": "squat",
  "Seated Box Jump": "squat",
  "Bodyweight Pulse Squat": "squat",
  "Pole Overhead Squat": "squat",
  "Bodyweight Alternating Curtsy Lunge": "lunge",
  "Bodyweight Kickstand Squat": "squat",
  "Machine Leg Press": "press",
  "Machine Hack Squat": "squat",
  "Machine Horizontal Sissy Leg Press": "press",
  "Machine Horizontal Leg Press": "press",
  "Machine Hip And Glute Kickback": "extension",
  "Kettlebell Single Leg Hip Thrust": "squat",
  "Kettlebell Step Up": "lunge",
  "Kettlebell Goblet Squat": "squat",
  "Kettlebell Heels Up Goblet Squat": "squat",
  "Kettlebell Single Arm Reverse Lunge": "lunge",
  "Kettlebell Lateral Lunge (Single)": "lunge",
  "Cable Standing Hip Adduction": "default",
  "Band Spanish Squat": "squat",
  "Band Leg Press": "press",
  "Band Squat": "squat",
  "Plate Reverse Lunge Twist": "lunge",
  "Vitruvian Belt Squat": "squat",
  "Cardio Assault Bike": "raise",
  "Cardio Step Out Jacks": "raise",
  "Treadmill Side Shuffle": "squat",
  "Cardio Jumping Jacks": "raise",
  "Cardio Band Press Jacks": "press",
  "Nordic Hamstring Curl": "curl",
  "Bodyweight Reverse Lunge": "lunge",
  "Machine Seated Leg Curl": "curl",
  "Kettlebell Pullover": "default",
  "Cable Lat Prayer": "default",
  "Band Pullover": "default",
  "Cable Rope Lat Prayer": "default",
  "Cable Straight Arm Pull In": "default",
  "Machine Neutral Row": "row",
  "Stretcher": "default",
  "Dumbbell Front Raise": "raise",
  "Dumbbell Seated Rear Delt Fly": "fly",
  "Kettlebell Front Raise": "raise",
  "Kettlebell Single Arm Rear Delt Fly": "fly",
  "Cable Upright Row": "row",
  "Band Face Pull": "raise",
  "Band Front Raise": "raise",
  "Barbell Front Raise": "raise",
  "Barbell Overhead Press": "press",
  "Barbell Upright Row": "row",
  "Dumbbell Seated Arnold Press": "press",
  "Dumbbell Arnold Press": "press",
  "Dumbbell Neutral Overhead Press": "press",
  "Dumbbell Overhead Press": "press",
  "Dumbbell Push Press": "press",
  "Landmine Seated Alternating Overhead Press": "press",
  "Landmine Seated Overhead Press": "press",
  "Landmine Single Arm Overhead Press": "press",
  "Landmine Single Arm Push Press": "press",
  "Bosu Ball Pike Pushup": "pushup",
  "Internally Rotated Seated Rear Delt Fly": "fly",
  "Cable Bar Front Raise": "raise",
  "Cable High Internally Rotated Reverse Fly": "fly",
  "Cable Low Bilateral Lateral Raise": "raise",
  "Cable Rope Upright Row": "row",
  "Cable Rope Mid Lateral Raise": "raise",
  "Kettlebell Upright Row": "row",
  "Dumbbell Bent Arm Lateral Raise": "raise",
  "Dumbbell Internally Rotated Rear Delt Fly": "fly",
  "Dumbbell Shoulder External Rotation": "raise",
  "Forward Arm Circle": "raise",
  "Kettlebell Bottoms Up Single Arm Overhead Press": "press",
  "Ring Standing Pushup": "pushup",
  "Dumbbell Lateral Raise": "raise",
  "Kettlebell Upright Row Single": "row",
  "Barbell Incline Bench Press": "press",
  "Cable Bench Press": "press",
  "Barbell High Incline Bench Press": "press",
  "Kettlebell Incline Bench Press": "press",
  "Cable Rope Kneeling Face Pull": "raise",
  "Dumbbell Seated Overhead Tricep Extension": "extension",
  "Bench Dips": "pushup",
  "Kettlebell Skull Crusher": "extension",
  "Kettlebell Standing Tricep Extension": "extension",
  "Kettlebell Decline Skull Crusher": "extension",
  "Diamond Push Ups": "pushup",
  "Barbell Close Grip Bench Press": "press",
  "Cable Cross Pushdown": "extension",
  "Band Skullcrusher": "extension",
  "Barbell Skullcrusher": "extension",
  "Barbell Overhead Tricep Extension": "extension",
  "Dumbbell Overhead Tricep Extension": "extension",
  "Barbell Floor Press": "press",
  "Dumbbell Guillotine Incline Bench Press": "press",
  "Dumbbell Single Arm Press": "press",
  "Kettlebell Guillotine Bench Press": "press",
  "Cable Bar Pushdown": "extension",
  "Cable Bar Reverse Grip Pushdown": "extension",
  "Cable Tricep Kickback": "extension",
  "Cable Single Arm Rope Pushdown": "extension",
  "Dumbbell Floor Press": "press",
  "Dumbbell Incline Skullover": "extension",
  "Bodyweight Box Assisted Dips": "pushup",
  "Bodyweight Diamond Knee Push Ups": "pushup",
  "Bodyweight Elevated Push Up": "pushup",
  "Bodyweight Incline Knee Push Up": "pushup",
  "Bodyweight Knee Push Ups": "pushup",
  "Bodyweight Knee Tricep Extension": "extension",
  "Bodyweight Tricep Extension": "extension",
  "Kettlebell Single Arm Press": "press",
  "Kettlebell Walkover Pushup": "pushup",
  "Incline Push Up": "pushup",
  "Decline Push Up": "pushup",
  "Neutral Chest Press": "press",
  "Cable Single Arm Incline Bench Press": "press",
  "Parralel Bar Dips": "pushup",
  "Machine Assisted Parralel Bar Dips": "pushup",
  "Machine Chest Press": "press",
  "Ring Skullcrusher": "extension",
  "Ring Standing Archer Pushup": "pushup",
  "Dumbbell Shrug": "raise",
  "Cable 30 Degree Shrug": "raise",
  "Cable Single Arm 30 Degree Shrug": "raise",
  "Bodyweight Pike Shrug": "raise",
  "Elevated Pike Shoulder Shrug": "raise",
  "Bodyweight Squat": "squat",
  "Cable Standing Leg Extension": "extension",
  "Machine Hip Adduction": "default",
  "Machine Hip And Glute Adduction": "default",
  "Kettlebell Single Arm Chest Fly": "fly",
  "Push Up": "pushup",
  "Medicine Ball Chest Press Slam": "press",
  "Medicine Ball Chest Press Toss": "press",
  "Kettlebell Pec Fly": "fly",
  "Cable Bench Chest Fly": "fly",
  "Cable Decline Bench Chest Fly": "fly",
  "Cable Single Arm Decline Bench Chest Fly": "fly",
  "Cardio Assault Bike Arms Only": "press",
  "Cable Incline Bench Press": "press",
  "Machine Pec Fly": "fly",
  "Ring Standing Chest Fly": "fly",
  "Dumbbell Wood Chopper": "default",
  "Kettlebell Wood Chopper": "default",
  "Band Wood Chopper": "default",
  "Band Pallof Press": "press",
  "Cable Pallof Press": "press",
  "Dumbbell Kneeling Wood Chopper": "default",
  "Dumbbell Hand Side Plank": "plank",
  "Dumbbell Elbow Side Plank": "plank",
  "Landmine Kneeling Twist": "situp",
  "Landmine Russian Twist": "situp",
  "Medicine Ball Half Kneeling Wood Chopper": "default",
  "Medicine Ball Rainbow Slam": "default",
  "Medicine Ball Wood Chopper": "default",
  "Landmine Stationary Twist": "situp",
  "Vitruvian Side Bend": "default",
  "Hand Side Plank Reach Through": "plank",
  "Cable Half Kneeling High To Low Wood Chopper": "default",
  "Cable Half Kneeling Low To High Wood Chopper": "default",
  "Cable Oblique Pushdown": "default",
  "Cable Side Bend": "default",
  "Oblique Crunch": "situp",
  "Oblique Jackknife": "default",
  "Windshield Wiper": "default",
  "Machine Overhand Overhead Press": "press",
  "Machine Overhand Row": "row",
  "Machine Reverse Fly": "fly",
  "Ring Rear Delt Fly": "fly"
};

export const getExerciseConfig = (exerciseName) => {
  const patternId = EXERCISE_MAPPINGS[exerciseName] || 'default';
  return MOVEMENT_PATTERNS[patternId];
};
